# BPM表單 {#bpm-forms}

## [BPM-物料申請](#bpm-pn)

請見 [\@ref(bpm-pn)] BPM-物料申請

------------------------------------------------------------------------

## [BPM-BOM申請](#bpm-bom)

請見 [\@ref(bpm-bom)] BPM-BOM申請

------------------------------------------------------------------------

## [BPM-預設製程(Routing)](#bpm-routing)

請見 [\@ref(bpm-routing)] BPM-預設製程(Routing)

------------------------------------------------------------------------

## [BPM-SPD Code申請](#bpm-spd)

請見 [\@ref(bpm-spd)] BPM-SPD Code申請

------------------------------------------------------------------------

## [物料異動 & 料號異動申請(批次)]{#bpm-pn-change}

💡 請先參閱 [***`P:\BU2_Dram\Public\Rebecca\BPM申請單\BPM-物料異動申請.pptx`***]{style="color:red;"}

-   若更改 Testing Level 須同步發[**ECN**](#bpm-ecn) [\@ref(bpm-ecn)]，並於物料異動單備註 ECN 編號

------------------------------------------------------------------------

## BOM變更申請單(批次) {#bpm-bom-change}

💡 請先參閱 [***`P:\BU2_Dram\Public\Rebecca\BPM申請單\BPM-BOM變更申請單(批次)-使用於變更插件位置.pptx`***]{style="color:red;"}

#### 請注意更改的是ES BOM 還是 MP BOM {.unnumbered}

-   更改 MP BOM 請改申請 [**ECN**](#bpm-ecn) [\@ref(bpm-ecn)]

-   若 PCB 有異動，則 BOM 變更完成後須發物料異動單更新 PCB 欄位

-   若需求為變更插件位置
    -   [WMS系統](http://192.168.21.165/Default.aspx){target="_blank"} → BOM /工單 → BOM 查詢，下載料號展開 BOM excel 檔，再進行修改 (插件位置每一個都要列出，且都要有英文字母)

    -   可用調整工具[^04-bpm表單-1]
        -   線上版，上傳**原始** excel 檔快速轉換、檢視、並下載: [**DRAM 插件位置轉換工具**](https://1a431p-0-0.shinyapps.io/DRAM-Placement-Adjust/){target="_blank"}
        -   excel 版，逐項輸入手動更改插件位置:

[^04-bpm表單-1]: 因第一項工具有每月流量限制，若無法正確執行請改用第二項 excel 版調整工具

```{r, echo=FALSE}
library(xfun)
xfun::embed_file("P:/BU2_Dram/Public/Rebecca/excel/插件位置調整工具.xlsx", text="2. 插件位置調整工具(excel 逐項更改)")
```

-   若需同時更改 STD PN 及相關 OEM PN，製作 excel 時請先列出 STD PN 再列出 OEM PN，否則系統會判斷錯誤無法申請

------------------------------------------------------------------------

## ECN申請單 {#bpm-ecn}

💡 請先參閱 [***`P:\BU2_Dram\Public\Rebecca\BPM申請單\BPM-ECN (Engineering Change Notice)申請單操作SOP，限MP BOM換料、測試代碼變更使用.pdf`***]{style="color:red;"}

-   僅限變更測試代碼、 MP BOM 換料使用、已出過貨之 OEM PN 更改 SOP
    -   ECN 生效後記得申請製程異動、更改對應特性值(若有異動)

------------------------------------------------------------------------

## [替代適用條件 & 替代料建立及異動申請單]{#bpm-substitute}

💡 請先參閱 [***`P:\BU2_Dram\Public\Rebecca\BPM申請單\BPM-替代料.pptx`***]{style="color:red;"}

### 替代適用條件

-   須附需求信件
-   需附主料&替代料之測報/ 出貨紀錄& PRN，若 EEPROM 不同需另外附上 EEPROM 替代適用條件 Report 畫面截圖
-   申請完成後，進入替代料建立&異動流程

### 替代料建立 & 異動

-   於備註說明 Priority, Usage Probability[^04-bpm表單-2] (若有需要)，由 SCM 設定
-   若[**關鍵零件**](#reapply-spd)有變更，則申請完成後，需申請 SPD Code

[^04-bpm表單-2]: Usage Probability: SCM 採買該料之比例

------------------------------------------------------------------------

## [製造通知單 (製通單]{#bpm-production-notice}

💡 請先參閱 [***`P:\BU2_Dram\Public\Rebecca\BPM申請單\BPM-製造通知單SOP_v1.0.pdf`***]{style="color:red;"}

送單後須截圖告知 Irons 製通單單號及 SPD Code 申請狀態 (Irons 看不到製通單資訊)

### 各組合適用流程

| [**PCB**]{style="color:red;"} | [**IC**]{style="color:red;"} | EVT | DVT | QFT | 開會 |
|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|
| [**新**]{style="color:green;"} | 新 | **V** | **V** |  | **V** |
| [**新**]{style="color:green;"} | 已驗 | **V** | **V** |  | **V** |
| 已驗 | 新 |  | V |  |  |
| 已驗 | 已驗 |  |  | V |  |

### 填單說明

-   需求日: 申請日 +7 工作天
-   負責 PM: Irons
-   備註說明:

1.  急單 2.使用 ES BOM 投產 3.QFT，全頻率驗證，提供全頻率驗證報告 4.標籤不用 ES 字樣 5.不需召開試產會議

-   描述說明:

驗證 PCB "" + DDR4-3200 "(原廠編碼)" for "客戶"送樣需求

------------------------------------------------------------------------

## 非生產領用雜發申請單 {#bpm-receipt}

-   先確認好庫存倉別 (若有綁訂單則高雄庫房會卡)
-   申請單備註收件人資訊(名字、地點、分機)，並於送單後寄信告知 **#TW_Warehouse** 收件人資訊

------------------------------------------------------------------------

## 員工借貨申請 & 借貨歸還申請單 {#bpm-borrow}

💡 請先參閱 [***`P:\BU2_Dram\Public\Rebecca\BPM申請單\BPM-借貨%20&%20歸還申請單.pptx`***]{style="color:red;"}

-   歸還時請在備註欄填寫回哪個倉以便 KH 判定
-   新廠為智能倉儲，目前歸還流程: 檢驗外觀 → 待判倉 → 生管開工單檢驗

---
